global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'formatbot'
    scrape_interval: 1m
    static_configs:
      - targets: ['formatbot:3000']
